/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.victoryw.fq.proxy;

import com.victoryw.fq.proxy.demo.HttpHelloWorldServer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.net.ssl.SSLException;
import java.security.cert.CertificateException;

public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        try {
            new HttpHelloWorldServer().run();
        } catch (InterruptedException | CertificateException | SSLException e) {
            logger.error("......",e);
        }
    }
}
